### ISSUE TITLE
[BUG] If Else Outcome is incorrectly taking settings from dictionary

### ISSUE THREAD

**Issue by mikita-sakalouski** [Nike-Inc/brickflow#171]
**Describe the bug**
When you are putting the if_else_condition_task type in the depends_on, you should provide dict with configuration of outcome lineage `if_else_outcome={"is_local": "false", "is_local2": "true"}`. The problem is that current implementation takes the first value and apply it for all tasks, instead of taking the value by task_name: 
```python
  @property
  def depends_on_names(self) -> Iterator[Dict[str, Optional[str]]]:
      for i in self.depends_on:
          if self.if_else_outcome:
              # Here is the issue
              outcome = list(self.if_else_outcome.values())[0]
          else:
              outcome = None

          if callable(i) and hasattr(i, "__name__"):
              yield {i.__name__: outcome}
          else:
              yield {str(i): outcome}
```

**To Reproduce**
1. Create workflow
```python
wf = Workflow(
    "test",
    default_cluster=Cluster.from_existing_cluster("existing_cluster_id"),
    schedule_quartz_expression="* * * * *",
    permissions=WorkflowPermissions(
        owner=User("abc@abc.com"),
        can_manage_run=[User("abc@abc.com")],
        can_view=[User("abc@abc.com")],
        can_manage=[User("abc@abc.com")],
    ),
    run_as_user="abc@abc.com",
    tags={"test": "test2"},
    common_task_parameters={"all_tasks1": "test", "all_tasks3": "123"},  # type: ignore
    health={
        "rules": [
            {"metric": "RUN_DURATION_SECONDS", "op": "GREATER_THAN", "value": 7200.0}
        ]
    },  # type: ignore
    trigger={
        "file_arrival": {"url": "<my_url>"},
        "pause_status": "UNPAUSED",
    },  # type: ignore
    parameters=[
        JobsParameters(
            default="value1",
            name="wf_param1",
        )
    ],
)
```
2. Create several if_condition_tasks
```python
@workflow.if_else_condition_task()
def is_local():
    return IfElseConditionTask(left="{{job.parameters.environment}}", op="==", right="local")


@workflow.if_else_condition_task()
def is_local2():
    return IfElseConditionTask(left="{{job.parameters.environment}}", op="==", right="local")
```
3. Create one normal task and put both if_condition_tasks in dependency
```python
@workflow.spark_python_task(
    depends_on=[is_local2, is_local], if_else_outcome={"is_local": "false", "is_local2": "true"}
)
def sync():
    return build_spark_python_task()
```
5. Run brickflow deploy
6. As result you will get the yaml which said 
```yaml
        - task_key: sync
          depends_on:
            - task_key: is_local2
              outcome: "false"
            - task_key: is_local
              outcome: "false"
```

**Expected behavior**
Outcome should be taken correctly based on the key, and not the first one. Generated yaml should look like: 
```yaml
        - task_key: sync
          depends_on:
            - task_key: is_local2
              outcome: "false"
            - task_key: is_local
              outcome: "true"
```

**Screenshots**
<img width="776" alt="Screenshot 2024-10-18 at 13 47 17" src="https://github.com/user-attachments/assets/f61cebc8-2735-4149-a76f-cfd2eeb7b6ed">
